config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #home route should be products
  root 'products#index'

  #have additional routes for the state machine transitions
  resources :products do
    get :open
    get :finish
    get :destash
    collection do
      get 'gone'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	validates_presence_of :brand
	validates_presence_of :name
	validates_presence_of :category


	#using aasm to track the state of each project within the collection
	include AASM

	aasm timestamps: true do
    state :unopen, initial: true
    state :open
    state :finished
    state :destashed

    after_all_transitions :log_state_date

    event :open do
      transitions from: :unopen, to: :open
    end

    event :finish do
      transitions from: :open, to: :finished
    end

    event :destash do
      transitions from: [:unopen, :open], to: :destashed
    end
  end

  #set scopes for common sorts and subsets of products
  scope :current, -> { where(aasm_state: ['unopen', 'open'])}
  scope :gone, -> { where(aasm_state: ['finished', 'destashed'])}

  def fullname
  	[self.brand, self.name].join(' ')
  end

  private

  	#setting the date the state changed which is logged
	  def log_state_date
	    self.aasm_state_date = Date.today
	    self.save
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update]

	def index
		@products = Product.current.order(:name)
		@total = @products.map(&:price).inject(:+)
		@areas = @products.map(&:face_area).uniq.sort
		@brands = @products.map(&:brand).uniq.sort
	end

	def show
    
  end

  def new
  end

  def edit
  end

  def create
    @product = Product.create(products_params)
    respond_with @product
  end

  def update
    @product.update(products_params)
    redirect_to @product
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def gone
  	@products = Product.gone
  end

  def open
  	@product = Product.find(params[:product_id])
    @product.open!
    redirect_to(@product)
  end

  def finish
  	@product = Product.find(params[:product_id])
    @product.finish!
    redirect_to(@product)
  end

  def destash
  	@product = Product.find(params[:product_id])
    @product.destash!
    redirect_to(@product)
  end

  private
  	def set_product
      @product = Product.find(params[:id])
    end

    def products_params
      params.require(:product).permit(
      	:brand,
  			:name,
  			:category,
  			:face_area,
  			:review,
  			:rating,
  			:purchase_date,
  			:retailer,
  			:repurchase,
  			:planned,
  			:price,
  			:online,
      	:size,
      	:shade,
      	:color
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makeups_helper.rb
module MakeupsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeupVanity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      Kristin's Makeup Vanity
    </header>
    <aside>
      <%= yield :sidebar %>
      <%= link_to "Add Product", new_product_path %>

    </aside>
    <main>
      <%= yield %>
    </main>
    <footer>
      
    </footer>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
	<%= form.label :brand, "Brand" %>
	<%= form.text_field :brand %>
	<%= form.label :name, "Name" %>
	<%= form.text_field :name %>
	<%= form.label :category, "Product Type" %>
	<%= form.text_field :category %>
	<%= form.label :face_area, "Product Group" %>
	<%= form.select :face_area, ["Base", "Cheek", "Eye", "Lip", "Other"] %>
	<%= form.label :face_area, "Size" %>
	<%= form.text_field :size %>
  <%= form.label :shade, "Shade Name" %>
  <%= form.text_field :shade %>
  <%= form.label :color, "Color (Hex Value)" %>
  <%= form.text_field :color %>
  <hr />
	<%= form.label :review, "Review" %>
	<%= form.text_area :review %>
	<%= form.label :rating, "Rating" %>
	
	<div id="stars" data-controller="star">
		<%= form.range_field :rating, min: 1, max: 5, class: 'hidden', data: {"star-target": "input"} %>
		<span data-star-value="1" data-star-target="star" data-action="click->star#selectStar">&star;</span>
		<span data-star-value="2" data-star-target="star" data-action="click->star#selectStar">&star;</span>
		<span data-star-value="3" data-star-target="star" data-action="click->star#selectStar">&star;</span>
		<span data-star-value="4" data-star-target="star" data-action="click->star#selectStar">&star;</span>
		<span data-star-value="5" data-star-target="star" data-action="click->star#selectStar">&star;</span>
	</div>
	<hr />
	<%= form.label :purchase_date, "Purchased On" %>
	<%= form.date_field :purchase_date %>
	<%= form.label :purchase_date, "Purchased From" %>
	<%= form.text_field :retailer %>
	<%= form.label :purchase_date, "Planned Purchase" %>
	<%= form.check_box :planned %>
	<%= form.label :price, "Price" %>
	<%= form.number_field :price %>
	<%= form.label :purchase_date, "Purchased Online" %>
	<%= form.check_box :online %>
  
  <%= form.submit %>
<% end %>

app/views/products/_product_details.html.erb
<article class="card" data-sname="<%= p.fullname %>" data-price="<%= p.price %>" data-state="<%= p.aasm_state %>" data-face="<%= p.face_area %>" data-brand="<%= p.brand %>"  data-type="<%= p.category %>" data-sort-target="card"  data-filter-target="card">
	<div class="details">
		<h1><%= link_to p.fullname, p %><%= " in "+ p.shade if !p.shade.blank? %></h1>
		<h2><%= number_to_currency(p.price) %> for <%= p.size ? p.size : "Full" %> size</h2>
		<%= p.aasm_state.humanize %><%= " since "+ p.aasm_state_date.to_s if p.aasm_state_date %>
	</div>
	<div class="swatch" style="background: <%= p.color %>; width: 10em"></div>
</article>

app/views/products/edit.html.erb
<h1>Update Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/gone.html.erb
<h2>Removed Products</h2>
<div data-controller="sort">
	<select name="sort" id="sort" data-action="sort#resort">
		<option value="name_desc" data-sort-direction="desc"  data-sort-value="sname">Name &darr;</option>
		<option value="name_desc" data-sort-direction="asc"  data-sort-value="sname">Name &uarr;</option>
		<option value="price_desc" data-sort-direction="desc"  data-sort-value="price">Price &darr;</option>
		<option value="price_desc" data-sort-direction="asc"  data-sort-value="price">Price &uarr;</option>
	</select>
	<div data-sort-target="container">
		<%= render partial: 'product_details', collection: @products, as: :p, cached: true %>
	</div>
</div>

<% content_for :sidebar do %>
	<%= link_to "View Vanity", products_path %>
<% end %>

app/views/products/index.html.erb
<div data-controller="sort filter">
	<div class="fcontainer">
		<div>
			<label for="sort">Sort</label>
			<select name="sort" id="sort" data-action="sort#resort">
				<option value="name_desc" data-sort-direction="desc"  data-sort-value="sname">Name &darr;</option>
				<option value="name_desc" data-sort-direction="asc"  data-sort-value="sname">Name &uarr;</option>
				<option value="price_desc" data-sort-direction="desc"  data-sort-value="price">Price &darr;</option>
				<option value="price_desc" data-sort-direction="asc"  data-sort-value="price">Price &uarr;</option>
			</select>
		</div>
		<div>
			<label for="face">Narrow by Area of Face</label>
			<% cache @areas do %>
			<select name="face" id="face" data-action="filter#filter">
				<option value="all">See All</option>
				<% @areas.each do |a| %>
					<option value="<%= a %>"><%= a %></option>
				<% end %>
			</select>
			<% end %>
		</div>
		<div>
			<% cache @brands do %>
				<label for="brand">Narrow by Brand</label>
				<select name="brand" id="brand" data-action="filter#filter">
					<option value="all">See All</option>
					<% @brands.each do |a| %>
						<option value="<%= a %>"><%= a %></option>
					<% end %>
				</select>
			<% end %>
		</div>
	</div>
	
	<div data-sort-target="container">
		<%= render partial: 'product_details', collection: @products, as: :p, cached: true %>
	</div>
</div>


<% content_for :sidebar do %>
	<h3>Current cost: <%= number_to_currency(@total) %></h3>
	<%= link_to "Removed Products", gone_products_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div style="display: flex;">
	<div class="details">
		<h1><%= @product.brand %> <%= @product.name %><%= " in "+ @product.shade if !@product.shade.blank? %></h1>
		<div id="stars">
				<% @product.rating.to_i.times do |r| %>
					<span>&starf;</span>
				<% end %>

	</div>
		<h2><%= number_to_currency(@product.price) %> for <%= @product.size ? @product.size : "Full" %> size</h2>
		<%= @product.aasm_state.humanize %><%= " since "+ @product.aasm_state_date.to_s if @product.aasm_state_date %>
	</div>
	<div class="swatch" style="background: <%= @product.color %>; width: 10em"></div>
</div>

<hr>
<h3>Purchase Details</h3>
<ul>
	<li>Purchased on <%= @product.purchase_date ? @product.purchase_date : "an unknown date" %> from <%= @product.retailer %> (<%= @product.online == true ? "Online" : "In Store" %>)</li>
	<% if @product.planned == true %><li>Planned Purchase</li><% end %>
</ul>

<% content_for :sidebar do %>
	<%= link_to "View Vanity", products_path %>
	<%= link_to "Edit Product", edit_product_path(@product) %>
	<%= link_to "I opened this product", product_open_path(@product) if @product.aasm_state == "unopen" %>
	<%= link_to "I destashed this product", product_destash_path(@product) if @product.aasm_state == "open" %>
	<%= link_to "I finished this product", product_finish_path(@product) if @product.aasm_state == "open" %>
<% end %>